---
title: "R Notebook"
output: html_notebook
---

### **2.2 The very basics**

Before we get started with the motivating dataset, we need to cover the very basics of R.

#### **2.2.1 Objects**

Suppose a high school student asks us for help solving several quadratic equations of the form $ax^2+bx+c=0.$
The quadratic formula gives us the solutions:

##### ${-b + \sqrt{b^2-4ac} \over 2a}$ and ${-b - \sqrt{b^2-4ac} \over 2a}$

which of course change depending on the values of $a$,$b$,and $c$. One advantage of programming languages is that we can define variables and write expressions with these variables, similar to how we do so in math, but obtain a numeric solution. We will write out general code for the quadratic equation below, but if we are asked to solve $x^2+x-1=0$, then we define:

```
a <- 1
b <- 1
c <- -1
```
which stores the values for later use. We use `<-` to assign values to the variables.

We can also assign values using `=` insted of `<-`, but we recommend against using `=` to avoid confusion.

Copy and paste the code above into your console to define the three variables. Note that R does not print anything when we make this assignment. This means the objects were defined successfully. Had you made a mistake, you would have received and error message.

To see the value stored in a varable, we simply ask R to evalutae `a` and it shows the stored value:
```
a
#> [1] 1
```

A more explicit way to ask R to show us the value stored in `a` is using `print` like this:
```
print(a)
#> [1] 1
```
We use the term object to describe stuff that is stored in R. Variables are examples, but objects can also be more complicated entities such as functions, which are described later.

#### **2.2.2 The workspace**

As we define objects in the console, we are actually changing the _workspace_. You can see all the variables saved in your workspace by typing:
```
ls()
#> [1] "a"        "b"        "c"        "dat"      "img_path" "murders"
```

In Rstudio, the _Environment_ tab shows the values:

ImageImageImageImageImageImageImageImageImageImageImageImageImage

We should see `a`,`b`,and `c`. If you try to recover the value of a variable that is not in your workspace, you receive an error. For example, if you type `x` you will receive the follwing message: `Error: object 'x' not found.`.

Now since these values are saved in variables, to obtain a solution to our equation, we use the quadratic formula:
```
(-b + sqrt(b^2 - 4*a*c) ) / ( 2*a )
#> [1] 0.618
(-b - sqrt(b^2 - 4*a*c) ) / ( 2*a )
#> [1] -1.62
```

#### *2.2.3 Functions*
Once you define variables, the data analysis process can usually be described as a series of _functions_ applied to the data. R includes several predefined functions and most of the analysis pipelines we construct make extensive use of these.

We already used the `install.packages`,`library`,and`ls` functions. We also used the function `sqrt` to solve the quadratic equation above. There are many more prebuilt functions and even more can be added through packages. These functions do not appear in the workspace because you did not define them, but they are available for immediate use.

In general, we need to use parentheses to evaluate a function. If you type `ls`, the function is not evaluated and instead R shows you the code that defines the function. If you type `ls()` the function is evaluated and, as seen above, we see objects in the workspace.

Unlike `ls`, most functions require one or more _argumnets_. Below is an example of how we assign an object to the argument of the function `log`. Remember that we earlier defined `a` to be 1:

```
log(8)
#> [1] 2.08
log(a)
#> [1] 0
```

You can find out whay the function expects and what it does by reviewing the very useful manuals included in R. You can get help by using the `help` function like this:

```
help("log")
```

For most functions, we can also use this shorthand:

```
?log
```

The help page will show you what arguments the function is expecting. For example, `log` needs `x` and `base` to run. However, some arguments are required and others are optional. You can determine which arguments are optional by noting in the help document that a default value is assigned with `=`. Defining these is optional. For example, the base of the function `log` defaults to `base = exp(1)` making `log` the natural log by default.

If you want a quick look at the arguments without opening the help system, you can type:

```
args(log)
#> function (x, base)
#> NULL
```

You can change the default values by simply assigning another object:

```
log(8, base = 2)
#> [1] 3
```

Note that we have not been specifying the argument `x` as such:

```
log(x = 8, base = 2)
#> [1] 3
```

The above code works, but we can save ourselves some typing: if no argument name is used, R assumes you are entering arguments in the order shown in the help file or by `args`. So by not using the names, it assumes the arguments are `x` follwed by `base`:

```
log(8,2)
#> [1] 3
```

If using the arguments' names, then we can include them in whatever order we want:

```
log(base = 2, x = 8)
#> [1] 3 
```

To specify arguments, we must use `=`, and cannot use `<-`.

There are some exceptions to the rule that functions need the parentheses to be evaluated. Among these, the most commonly used are the arithmetic and relational operators.For example:

```
2^3
#> [1] 8
```

You can see the arithmetic operators by typing:

```
help("+")
```

or

```
?"+"
```

and the relational operators by typing:

```
help(">")
```

or

```
?">"
```

#### **2.2.4 Other prebulit objects**

There are several datasets that are included for users to practice and test out functions. You can see all the available datasets by typing:

```
data()
```

This shows you the object name for these datasets. These datasets are objects that can be used by simply typing the name. For example, if you type:

```
co2
```

R will show you Mauna Loa atmospheric CO2 concentration data.

Other prebuilt objects are mathematical quantities, such as the constant $π$ and $∞$:

```
pi
#> [1] 3.14
Inf+1
#> [1] Inf
```

#### **2.2.5 Variable names**

We have used the letters `a`, `b`, and `c` as variable names, but variable names can be almost anything. Some basic rules in R are that variable names have to start with a letter, can't contain spaces, and should not be variables that are predefined in R. For example, don't name one of your variables `install.packages` by typing something like `install.packages <- 2`.

A nice convention to follow is to use meaningful words that describe what is stored, use only lower case, and use underscores as a substitute for spaces. For the quadratic equations, we could use something like this:

```
solution_1 <- (-b + sqrt(b^2 - 4*a*c)) / (2*a)
solution_2 <- (-b - sqrt(b^2 - 4*a*c)) / (2*a)
```

For mroe advice, we highly recommed studying Hadley Wickham's style guide.

#### **2.2.6 Saving your workspace**

Values remain in the workspace until you end your session or erase them with the function `rm`. But workspaces also can be saved for later use. In fact, when you quit R, the program asks you if you want to save your workspace. If you do save it, the next time you start R, the program will restore the workspace.

We actually recommend against saving the workspace this way because, as you start working on different projects, it will become harder to keep track of what is saved. Instead, we recommend you assign the workspace a specific name. You can do this by using the function `save` or `save.image`. To load, use the function `load`. When saving a workspace, we recommed the suffix `rda` or `RData`. In Rstudio, you can also do this by navigating to the _Session_ tab and choosing _Save Workspace_ as. You can later load it using the _Load Workspace_ options in the same tab. You can read the help pages on `save`, `save.image`, and `load` to learn more.
